StylesPath = validation/styles
Vocab = Technical

MinAlertLevel = warning

Packages = proselint, write-good, alex, Joblint, MDX

[*.{md}]
BasedOnStyles = proselint, write-good, alex, Joblint

# Disable rules that are too strict for technical documentation
write-good.E-Prime = NO
write-good.Passive = suggestion
alex.ProfanityUnlikely = NO
alex.Ablist = NO
write-good.TooWordy = suggestion
Joblint.Benefits = NO
