"""
Enumerations for OANDA API.

Contains all enum types used throughout the OANDA API models.
"""

from decimal import Decimal
from enum import Enum


# Core Enums
class Currency(str, Enum):
    """ISO 4217 currency codes supported by OANDA."""

    AUD = "AUD"  # Australian Dollar
    CAD = "CAD"  # Canadian Dollar
    CHF = "CHF"  # Swiss Franc
    CNH = "CNH"  # Chinese Yuan (Offshore)
    CZK = "CZK"  # Czech Koruna
    DKK = "DKK"  # Danish Krone
    EUR = "EUR"  # Euro
    GBP = "GBP"  # British Pound
    HKD = "HKD"  # Hong Kong Dollar
    HUF = "HUF"  # Hungarian Forint
    JPY = "JPY"  # Japanese Yen
    MXN = "MXN"  # Mexican Peso
    NOK = "NOK"  # Norwegian Krone
    NZD = "NZD"  # New Zealand Dollar
    PLN = "PLN"  # Polish Zloty
    SEK = "SEK"  # Swedish Krona
    SGD = "SGD"  # Singapore Dollar
    THB = "THB"  # Thai Baht
    TRY = "TRY"  # Turkish Lira
    USD = "USD"  # United States Dollar
    ZAR = "ZAR"  # South African Rand


class InstrumentName(str, Enum):
    """Available trading instruments - complete list from OANDA."""

    # AUD pairs
    AUD_CAD = "AUD_CAD"
    AUD_CHF = "AUD_CHF"
    AUD_HKD = "AUD_HKD"
    AUD_JPY = "AUD_JPY"
    AUD_NZD = "AUD_NZD"
    AUD_SGD = "AUD_SGD"
    AUD_USD = "AUD_USD"

    # CAD pairs
    CAD_CHF = "CAD_CHF"
    CAD_HKD = "CAD_HKD"
    CAD_JPY = "CAD_JPY"
    CAD_SGD = "CAD_SGD"

    # CHF pairs
    CHF_HKD = "CHF_HKD"
    CHF_JPY = "CHF_JPY"
    CHF_ZAR = "CHF_ZAR"

    # EUR pairs
    EUR_AUD = "EUR_AUD"
    EUR_CAD = "EUR_CAD"
    EUR_CHF = "EUR_CHF"
    EUR_CZK = "EUR_CZK"
    EUR_DKK = "EUR_DKK"
    EUR_GBP = "EUR_GBP"
    EUR_HKD = "EUR_HKD"
    EUR_HUF = "EUR_HUF"
    EUR_JPY = "EUR_JPY"
    EUR_NOK = "EUR_NOK"
    EUR_NZD = "EUR_NZD"
    EUR_PLN = "EUR_PLN"
    EUR_SEK = "EUR_SEK"
    EUR_SGD = "EUR_SGD"
    EUR_TRY = "EUR_TRY"
    EUR_USD = "EUR_USD"
    EUR_ZAR = "EUR_ZAR"

    # GBP pairs
    GBP_AUD = "GBP_AUD"
    GBP_CAD = "GBP_CAD"
    GBP_CHF = "GBP_CHF"
    GBP_HKD = "GBP_HKD"
    GBP_JPY = "GBP_JPY"
    GBP_NZD = "GBP_NZD"
    GBP_PLN = "GBP_PLN"
    GBP_SGD = "GBP_SGD"
    GBP_USD = "GBP_USD"
    GBP_ZAR = "GBP_ZAR"

    # HKD pairs
    HKD_JPY = "HKD_JPY"

    # NZD pairs
    NZD_CAD = "NZD_CAD"
    NZD_CHF = "NZD_CHF"
    NZD_HKD = "NZD_HKD"
    NZD_JPY = "NZD_JPY"
    NZD_SGD = "NZD_SGD"
    NZD_USD = "NZD_USD"

    # SGD pairs
    SGD_CHF = "SGD_CHF"
    SGD_JPY = "SGD_JPY"

    # TRY pairs
    TRY_JPY = "TRY_JPY"

    # USD pairs
    USD_CAD = "USD_CAD"
    USD_CHF = "USD_CHF"
    USD_CNH = "USD_CNH"
    USD_CZK = "USD_CZK"
    USD_DKK = "USD_DKK"
    USD_HKD = "USD_HKD"
    USD_HUF = "USD_HUF"
    USD_JPY = "USD_JPY"
    USD_MXN = "USD_MXN"
    USD_NOK = "USD_NOK"
    USD_PLN = "USD_PLN"
    USD_SEK = "USD_SEK"
    USD_SGD = "USD_SGD"
    USD_THB = "USD_THB"
    USD_TRY = "USD_TRY"
    USD_ZAR = "USD_ZAR"

    # ZAR pairs
    ZAR_JPY = "ZAR_JPY"


class InstrumentType(str, Enum):
    """Types of trading instruments."""

    CURRENCY = "CURRENCY"
    CFD = "CFD"
    METAL = "METAL"


class OrderType(str, Enum):
    """Order types."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    MARKET_IF_TOUCHED = "MARKET_IF_TOUCHED"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    GUARANTEED_STOP_LOSS = "GUARANTEED_STOP_LOSS"
    TRAILING_STOP_LOSS = "TRAILING_STOP_LOSS"
    FIXED_PRICE = "FIXED_PRICE"


class OrderState(str, Enum):
    """Order states."""

    PENDING = "PENDING"
    FILLED = "FILLED"
    TRIGGERED = "TRIGGERED"
    CANCELLED = "CANCELLED"


class Direction(str, Enum):
    """Position direction."""

    LONG = "LONG"
    SHORT = "SHORT"


class TradeState(str, Enum):
    """The current state of a Trade."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CLOSE_WHEN_TRADEABLE = "CLOSE_WHEN_TRADEABLE"


class TimeInForce(str, Enum):
    """Time in force for orders."""

    GTC = "GTC"  # Good Till Cancelled
    GTD = "GTD"  # Good Till Date
    GFD = "GFD"  # Good For Day
    FOK = "FOK"  # Fill Or Kill
    IOC = "IOC"  # Immediate Or Cancel


class OrderPositionFill(str, Enum):
    """How an Order should be filled into existing Positions."""

    OPEN_ONLY = "OPEN_ONLY"
    REDUCE_FIRST = "REDUCE_FIRST"
    REDUCE_ONLY = "REDUCE_ONLY"
    DEFAULT = "DEFAULT"


class OrderTriggerCondition(str, Enum):
    """Condition that must be satisfied before Order becomes fillable."""

    DEFAULT = "DEFAULT"
    INVERSE = "INVERSE"
    BID = "BID"
    ASK = "ASK"
    MID = "MID"


class CandlestickGranularity(str, Enum):
    """Time intervals for candlestick data."""

    # Second-based intervals (minute aligned)
    S5 = "S5"
    S10 = "S10"
    S15 = "S15"
    S30 = "S30"

    # Minute-based intervals (hour aligned)
    M1 = "M1"
    M2 = "M2"
    M4 = "M4"
    M5 = "M5"
    M10 = "M10"
    M15 = "M15"
    M30 = "M30"

    # Hour-based intervals (day aligned)
    H1 = "H1"
    H2 = "H2"
    H3 = "H3"
    H4 = "H4"
    H6 = "H6"
    H8 = "H8"
    H12 = "H12"

    # Day-based intervals (week aligned)
    D = "D"

    # Week-based intervals (month aligned)
    W = "W"

    # Month-based intervals (year aligned)
    M = "M"


class WeeklyAlignment(str, Enum):
    """Days of the week for weekly alignment."""

    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"
    SUNDAY = "Sunday"


class DailyAlignment(int, Enum):
    """Hours for daily alignment (0-23)."""

    MIDNIGHT = 0
    H01 = 1
    H02 = 2
    H03 = 3
    H04 = 4
    H05 = 5
    H06 = 6
    H07 = 7
    H08 = 8
    H09 = 9
    H10 = 10
    H11 = 11
    NOON = 12
    H13 = 13
    H14 = 14
    H15 = 15
    H16 = 16
    H17 = 17
    H18 = 18
    H19 = 19
    H20 = 20
    H21 = 21
    H22 = 22
    H23 = 23


class AcceptDatetimeFormat(str, Enum):
    """Format for DateTime fields in OANDA requests and responses."""

    UNIX = "UNIX"
    RFC3339 = "RFC3339"


class TransactionType(str, Enum):
    """Types of transactions that can occur."""

    # Account Management
    CREATE = "CREATE"
    CLOSE = "CLOSE"
    REOPEN = "REOPEN"
    CLIENT_CONFIGURE = "CLIENT_CONFIGURE"
    CLIENT_CONFIGURE_REJECT = "CLIENT_CONFIGURE_REJECT"

    # Fund Management
    TRANSFER_FUNDS = "TRANSFER_FUNDS"
    TRANSFER_FUNDS_REJECT = "TRANSFER_FUNDS_REJECT"

    # Order Management
    MARKET_ORDER = "MARKET_ORDER"
    MARKET_ORDER_REJECT = "MARKET_ORDER_REJECT"
    FIXED_PRICE_ORDER = "FIXED_PRICE_ORDER"
    LIMIT_ORDER = "LIMIT_ORDER"
    LIMIT_ORDER_REJECT = "LIMIT_ORDER_REJECT"
    STOP_ORDER = "STOP_ORDER"
    STOP_ORDER_REJECT = "STOP_ORDER_REJECT"
    MARKET_IF_TOUCHED_ORDER = "MARKET_IF_TOUCHED_ORDER"
    MARKET_IF_TOUCHED_ORDER_REJECT = "MARKET_IF_TOUCHED_ORDER_REJECT"
    TAKE_PROFIT_ORDER = "TAKE_PROFIT_ORDER"
    TAKE_PROFIT_ORDER_REJECT = "TAKE_PROFIT_ORDER_REJECT"
    STOP_LOSS_ORDER = "STOP_LOSS_ORDER"
    STOP_LOSS_ORDER_REJECT = "STOP_LOSS_ORDER_REJECT"
    GUARANTEED_STOP_LOSS_ORDER = "GUARANTEED_STOP_LOSS_ORDER"
    GUARANTEED_STOP_LOSS_ORDER_REJECT = "GUARANTEED_STOP_LOSS_ORDER_REJECT"
    TRAILING_STOP_LOSS_ORDER = "TRAILING_STOP_LOSS_ORDER"
    TRAILING_STOP_LOSS_ORDER_REJECT = "TRAILING_STOP_LOSS_ORDER_REJECT"

    # Order Lifecycle
    ORDER_FILL = "ORDER_FILL"
    ORDER_CANCEL = "ORDER_CANCEL"
    ORDER_CANCEL_REJECT = "ORDER_CANCEL_REJECT"
    ORDER_CLIENT_EXTENSIONS_MODIFY = "ORDER_CLIENT_EXTENSIONS_MODIFY"
    ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT = "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"

    # Trade Management
    TRADE_CLIENT_EXTENSIONS_MODIFY = "TRADE_CLIENT_EXTENSIONS_MODIFY"
    TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT = "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"

    # Position Management
    MARGIN_CALL_ENTER = "MARGIN_CALL_ENTER"
    MARGIN_CALL_EXTEND = "MARGIN_CALL_EXTEND"
    MARGIN_CALL_EXIT = "MARGIN_CALL_EXIT"
    DELAYED_TRADE_CLOSURE = "DELAYED_TRADE_CLOSURE"

    # Financing
    DAILY_FINANCING = "DAILY_FINANCING"
    DIVIDEND_ADJUSTMENT = "DIVIDEND_ADJUSTMENT"

    # Miscellaneous
    RESET_RESETTABLE_PL = "RESET_RESETTABLE_PL"


class TransactionFilter(str, Enum):
    """Transaction type filters accepted by OANDA transaction list endpoints."""

    ORDER = "ORDER"
    FUNDING = "FUNDING"
    ADMIN = "ADMIN"
    CREATE = "CREATE"
    CLOSE = "CLOSE"
    REOPEN = "REOPEN"
    CLIENT_CONFIGURE = "CLIENT_CONFIGURE"
    CLIENT_CONFIGURE_REJECT = "CLIENT_CONFIGURE_REJECT"
    TRANSFER_FUNDS = "TRANSFER_FUNDS"
    TRANSFER_FUNDS_REJECT = "TRANSFER_FUNDS_REJECT"
    MARKET_ORDER = "MARKET_ORDER"
    MARKET_ORDER_REJECT = "MARKET_ORDER_REJECT"
    LIMIT_ORDER = "LIMIT_ORDER"
    LIMIT_ORDER_REJECT = "LIMIT_ORDER_REJECT"
    STOP_ORDER = "STOP_ORDER"
    STOP_ORDER_REJECT = "STOP_ORDER_REJECT"
    MARKET_IF_TOUCHED_ORDER = "MARKET_IF_TOUCHED_ORDER"
    MARKET_IF_TOUCHED_ORDER_REJECT = "MARKET_IF_TOUCHED_ORDER_REJECT"
    TAKE_PROFIT_ORDER = "TAKE_PROFIT_ORDER"
    TAKE_PROFIT_ORDER_REJECT = "TAKE_PROFIT_ORDER_REJECT"
    STOP_LOSS_ORDER = "STOP_LOSS_ORDER"
    STOP_LOSS_ORDER_REJECT = "STOP_LOSS_ORDER_REJECT"
    GUARANTEED_STOP_LOSS_ORDER = "GUARANTEED_STOP_LOSS_ORDER"
    GUARANTEED_STOP_LOSS_ORDER_REJECT = "GUARANTEED_STOP_LOSS_ORDER_REJECT"
    TRAILING_STOP_LOSS_ORDER = "TRAILING_STOP_LOSS_ORDER"
    TRAILING_STOP_LOSS_ORDER_REJECT = "TRAILING_STOP_LOSS_ORDER_REJECT"
    ONE_CANCELS_ALL_ORDER = "ONE_CANCELS_ALL_ORDER"
    ONE_CANCELS_ALL_ORDER_REJECT = "ONE_CANCELS_ALL_ORDER_REJECT"
    ONE_CANCELS_ALL_ORDER_TRIGGERED = "ONE_CANCELS_ALL_ORDER_TRIGGERED"
    ORDER_FILL = "ORDER_FILL"
    ORDER_CANCEL = "ORDER_CANCEL"
    ORDER_CANCEL_REJECT = "ORDER_CANCEL_REJECT"
    ORDER_CLIENT_EXTENSIONS_MODIFY = "ORDER_CLIENT_EXTENSIONS_MODIFY"
    ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT = "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
    TRADE_CLIENT_EXTENSIONS_MODIFY = "TRADE_CLIENT_EXTENSIONS_MODIFY"
    TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT = "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
    MARGIN_CALL_ENTER = "MARGIN_CALL_ENTER"
    MARGIN_CALL_EXTEND = "MARGIN_CALL_EXTEND"
    MARGIN_CALL_EXIT = "MARGIN_CALL_EXIT"
    DELAYED_TRADE_CLOSURE = "DELAYED_TRADE_CLOSURE"
    DAILY_FINANCING = "DAILY_FINANCING"
    RESET_RESETTABLE_PL = "RESET_RESETTABLE_PL"


class TransactionRejectReason(str, Enum):
    """Reasons why a transaction may be rejected.

    Sourced from OANDA REST v20 docs at https://developer.oanda.com/rest-live-v20/transaction-df/
    """

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INSTRUMENT_PRICE_UNKNOWN = "INSTRUMENT_PRICE_UNKNOWN"
    ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_ORDER_CREATION_LOCKED = "ACCOUNT_ORDER_CREATION_LOCKED"
    ACCOUNT_CONFIGURATION_LOCKED = "ACCOUNT_CONFIGURATION_LOCKED"
    ACCOUNT_DEPOSIT_LOCKED = "ACCOUNT_DEPOSIT_LOCKED"
    ACCOUNT_WITHDRAWAL_LOCKED = "ACCOUNT_WITHDRAWAL_LOCKED"
    ACCOUNT_ORDER_CANCEL_LOCKED = "ACCOUNT_ORDER_CANCEL_LOCKED"
    INSTRUMENT_NOT_TRADEABLE = "INSTRUMENT_NOT_TRADEABLE"
    PENDING_ORDERS_ALLOWED_EXCEEDED = "PENDING_ORDERS_ALLOWED_EXCEEDED"
    ORDER_ID_UNSPECIFIED = "ORDER_ID_UNSPECIFIED"
    ORDER_DOESNT_EXIST = "ORDER_DOESNT_EXIST"
    ORDER_IDENTIFIER_INCONSISTENCY = "ORDER_IDENTIFIER_INCONSISTENCY"
    TRADE_ID_UNSPECIFIED = "TRADE_ID_UNSPECIFIED"
    TRADE_DOESNT_EXIST = "TRADE_DOESNT_EXIST"
    TRADE_IDENTIFIER_INCONSISTENCY = "TRADE_IDENTIFIER_INCONSISTENCY"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    INSTRUMENT_MISSING = "INSTRUMENT_MISSING"
    INSTRUMENT_UNKNOWN = "INSTRUMENT_UNKNOWN"
    UNITS_MISSING = "UNITS_MISSING"
    UNITS_INVALID = "UNITS_INVALID"
    UNITS_PRECISION_EXCEEDED = "UNITS_PRECISION_EXCEEDED"
    UNITS_LIMIT_EXCEEDED = "UNITS_LIMIT_EXCEEDED"
    UNITS_MINIMUM_NOT_MET = "UNITS_MINIMUM_NOT_MET"
    PRICE_MISSING = "PRICE_MISSING"
    PRICE_INVALID = "PRICE_INVALID"
    PRICE_PRECISION_EXCEEDED = "PRICE_PRECISION_EXCEEDED"
    PRICE_DISTANCE_MISSING = "PRICE_DISTANCE_MISSING"
    PRICE_DISTANCE_INVALID = "PRICE_DISTANCE_INVALID"
    PRICE_DISTANCE_PRECISION_EXCEEDED = "PRICE_DISTANCE_PRECISION_EXCEEDED"
    PRICE_DISTANCE_MAXIMUM_EXCEEDED = "PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    PRICE_DISTANCE_MINIMUM_NOT_MET = "PRICE_DISTANCE_MINIMUM_NOT_MET"
    TIME_IN_FORCE_MISSING = "TIME_IN_FORCE_MISSING"
    TIME_IN_FORCE_INVALID = "TIME_IN_FORCE_INVALID"
    TIME_IN_FORCE_GTD_TIMESTAMP_MISSING = "TIME_IN_FORCE_GTD_TIMESTAMP_MISSING"
    TIME_IN_FORCE_GTD_TIMESTAMP_IN_PAST = "TIME_IN_FORCE_GTD_TIMESTAMP_IN_PAST"
    PRICE_BOUND_INVALID = "PRICE_BOUND_INVALID"
    PRICE_BOUND_PRECISION_EXCEEDED = "PRICE_BOUND_PRECISION_EXCEEDED"
    ORDERS_ON_FILL_DUPLICATE_CLIENT_ORDER_IDS = "ORDERS_ON_FILL_DUPLICATE_CLIENT_ORDER_IDS"
    TRADE_ON_FILL_CLIENT_EXTENSIONS_NOT_SUPPORTED = "TRADE_ON_FILL_CLIENT_EXTENSIONS_NOT_SUPPORTED"
    CLIENT_ORDER_ID_INVALID = "CLIENT_ORDER_ID_INVALID"
    CLIENT_ORDER_ID_ALREADY_EXISTS = "CLIENT_ORDER_ID_ALREADY_EXISTS"
    CLIENT_ORDER_TAG_INVALID = "CLIENT_ORDER_TAG_INVALID"
    CLIENT_ORDER_COMMENT_INVALID = "CLIENT_ORDER_COMMENT_INVALID"
    CLIENT_TRADE_ID_INVALID = "CLIENT_TRADE_ID_INVALID"
    CLIENT_TRADE_ID_ALREADY_EXISTS = "CLIENT_TRADE_ID_ALREADY_EXISTS"
    CLIENT_TRADE_TAG_INVALID = "CLIENT_TRADE_TAG_INVALID"
    CLIENT_TRADE_COMMENT_INVALID = "CLIENT_TRADE_COMMENT_INVALID"
    ORDER_FILL_POSITION_ACTION_MISSING = "ORDER_FILL_POSITION_ACTION_MISSING"
    ORDER_FILL_POSITION_ACTION_INVALID = "ORDER_FILL_POSITION_ACTION_INVALID"
    TRIGGER_CONDITION_MISSING = "TRIGGER_CONDITION_MISSING"
    TRIGGER_CONDITION_INVALID = "TRIGGER_CONDITION_INVALID"
    ORDER_PARTIAL_FILL_OPTION_MISSING = "ORDER_PARTIAL_FILL_OPTION_MISSING"
    ORDER_PARTIAL_FILL_OPTION_INVALID = "ORDER_PARTIAL_FILL_OPTION_INVALID"
    INVALID_REISSUE_IMMEDIATE_PARTIAL_FILL = "INVALID_REISSUE_IMMEDIATE_PARTIAL_FILL"
    ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION = "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION"
    ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION = "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION"
    TAKE_PROFIT_ORDER_ALREADY_EXISTS = "TAKE_PROFIT_ORDER_ALREADY_EXISTS"
    TAKE_PROFIT_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD = "TAKE_PROFIT_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD"
    TAKE_PROFIT_ON_FILL_PRICE_MISSING = "TAKE_PROFIT_ON_FILL_PRICE_MISSING"
    TAKE_PROFIT_ON_FILL_PRICE_INVALID = "TAKE_PROFIT_ON_FILL_PRICE_INVALID"
    TAKE_PROFIT_ON_FILL_PRICE_PRECISION_EXCEEDED = "TAKE_PROFIT_ON_FILL_PRICE_PRECISION_EXCEEDED"
    TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_MISSING = "TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_MISSING"
    TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_INVALID = "TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_INVALID"
    TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_MISSING = "TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_MISSING"
    TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST = "TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_INVALID = "TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_INVALID"
    TAKE_PROFIT_ON_FILL_CLIENT_ORDER_TAG_INVALID = "TAKE_PROFIT_ON_FILL_CLIENT_ORDER_TAG_INVALID"
    TAKE_PROFIT_ON_FILL_CLIENT_ORDER_COMMENT_INVALID = "TAKE_PROFIT_ON_FILL_CLIENT_ORDER_COMMENT_INVALID"
    TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_MISSING = "TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_MISSING"
    TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_INVALID = "TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_INVALID"
    STOP_LOSS_ORDER_ALREADY_EXISTS = "STOP_LOSS_ORDER_ALREADY_EXISTS"
    STOP_LOSS_ORDER_GUARANTEED_REQUIRED = "STOP_LOSS_ORDER_GUARANTEED_REQUIRED"
    STOP_LOSS_ORDER_GUARANTEED_PRICE_WITHIN_SPREAD = "STOP_LOSS_ORDER_GUARANTEED_PRICE_WITHIN_SPREAD"
    STOP_LOSS_ORDER_GUARANTEED_NOT_ALLOWED = "STOP_LOSS_ORDER_GUARANTEED_NOT_ALLOWED"
    STOP_LOSS_ORDER_GUARANTEED_HALTED_CREATE_VIOLATION = "STOP_LOSS_ORDER_GUARANTEED_HALTED_CREATE_VIOLATION"
    STOP_LOSS_ORDER_GUARANTEED_HALTED_TIGHTEN_VIOLATION = "STOP_LOSS_ORDER_GUARANTEED_HALTED_TIGHTEN_VIOLATION"
    STOP_LOSS_ORDER_GUARANTEED_HEDGING_NOT_ALLOWED = "STOP_LOSS_ORDER_GUARANTEED_HEDGING_NOT_ALLOWED"
    STOP_LOSS_ORDER_GUARANTEED_MINIMUM_DISTANCE_NOT_MET = "STOP_LOSS_ORDER_GUARANTEED_MINIMUM_DISTANCE_NOT_MET"
    STOP_LOSS_ORDER_NOT_CANCELABLE = "STOP_LOSS_ORDER_NOT_CANCELABLE"
    STOP_LOSS_ORDER_NOT_REPLACEABLE = "STOP_LOSS_ORDER_NOT_REPLACEABLE"
    STOP_LOSS_ORDER_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED = "STOP_LOSS_ORDER_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED"
    STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED = "STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED"
    STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING = "STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING"
    STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD = "STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD"
    STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION = "STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION"
    STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION = "STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION"
    STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER = "STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER"
    STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED = "STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED"
    STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED = "STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED"
    STOP_LOSS_ON_FILL_PRICE_MISSING = "STOP_LOSS_ON_FILL_PRICE_MISSING"
    STOP_LOSS_ON_FILL_PRICE_INVALID = "STOP_LOSS_ON_FILL_PRICE_INVALID"
    STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED = "STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED"
    STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET = "STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET"
    STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED = "STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED"
    STOP_LOSS_ON_FILL_DISTANCE_INVALID = "STOP_LOSS_ON_FILL_DISTANCE_INVALID"
    STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED = "STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED"
    STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED = "STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED"
    STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING = "STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING"
    STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING = "STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING"
    STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID = "STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID"
    STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING = "STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING"
    STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID = "STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID"
    STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID = "STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID"
    STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID = "STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID"
    STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING = "STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING"
    STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID = "STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID"
    GUARANTEED_STOP_LOSS_ORDER_ALREADY_EXISTS = "GUARANTEED_STOP_LOSS_ORDER_ALREADY_EXISTS"
    GUARANTEED_STOP_LOSS_ORDER_REQUIRED = "GUARANTEED_STOP_LOSS_ORDER_REQUIRED"
    GUARANTEED_STOP_LOSS_ORDER_PRICE_WITHIN_SPREAD = "GUARANTEED_STOP_LOSS_ORDER_PRICE_WITHIN_SPREAD"
    GUARANTEED_STOP_LOSS_ORDER_NOT_ALLOWED = "GUARANTEED_STOP_LOSS_ORDER_NOT_ALLOWED"
    GUARANTEED_STOP_LOSS_ORDER_HALTED_CREATE_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_HALTED_CREATE_VIOLATION"
    GUARANTEED_STOP_LOSS_ORDER_CREATE_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_CREATE_VIOLATION"
    GUARANTEED_STOP_LOSS_ORDER_HALTED_TIGHTEN_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_HALTED_TIGHTEN_VIOLATION"
    GUARANTEED_STOP_LOSS_ORDER_TIGHTEN_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_TIGHTEN_VIOLATION"
    GUARANTEED_STOP_LOSS_ORDER_HEDGING_NOT_ALLOWED = "GUARANTEED_STOP_LOSS_ORDER_HEDGING_NOT_ALLOWED"
    GUARANTEED_STOP_LOSS_ORDER_MINIMUM_DISTANCE_NOT_MET = "GUARANTEED_STOP_LOSS_ORDER_MINIMUM_DISTANCE_NOT_MET"
    GUARANTEED_STOP_LOSS_ORDER_NOT_CANCELABLE = "GUARANTEED_STOP_LOSS_ORDER_NOT_CANCELABLE"
    GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_CANCELABLE = "GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_CANCELABLE"
    GUARANTEED_STOP_LOSS_ORDER_NOT_REPLACEABLE = "GUARANTEED_STOP_LOSS_ORDER_NOT_REPLACEABLE"
    GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_REPLACEABLE = "GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_REPLACEABLE"
    GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_VOLUME_EXCEEDED = "GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_VOLUME_EXCEEDED"
    GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED = "GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED"
    GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED = "GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED"
    GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING = "GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING"
    GUARANTEED_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD = "GUARANTEED_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD"
    GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION"
    GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION = "GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION"
    GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER = "GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER"
    GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED = "GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED"
    GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED = "GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_MISSING = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_MISSING"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET = "GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET"
    GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING"
    GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING = "GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING"
    GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING = "GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING"
    GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING = "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING"
    GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID"
    TRAILING_STOP_LOSS_ORDER_ALREADY_EXISTS = "TRAILING_STOP_LOSS_ORDER_ALREADY_EXISTS"
    TRAILING_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD = "TRAILING_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD"
    TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION = "TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION"
    TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION = "TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION"
    TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MISSING = "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MISSING"
    TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_INVALID = "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_INVALID"
    TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_PRECISION_EXCEEDED = "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_PRECISION_EXCEEDED"
    TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MINIMUM_NOT_MET = "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MINIMUM_NOT_MET"
    TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING = "TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING"
    TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID = "TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID"
    TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING = "TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING"
    TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID = "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID"
    TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID = "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID"
    TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID = "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID"
    TRAILING_STOP_LOSS_ORDERS_NOT_SUPPORTED = "TRAILING_STOP_LOSS_ORDERS_NOT_SUPPORTED"
    TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING = "TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING"
    TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID = "TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID"
    CLOSE_TRADE_TYPE_MISSING = "CLOSE_TRADE_TYPE_MISSING"
    CLOSE_TRADE_PARTIAL_UNITS_MISSING = "CLOSE_TRADE_PARTIAL_UNITS_MISSING"
    CLOSE_TRADE_UNITS_EXCEED_TRADE_SIZE = "CLOSE_TRADE_UNITS_EXCEED_TRADE_SIZE"
    CLOSEOUT_POSITION_DOESNT_EXIST = "CLOSEOUT_POSITION_DOESNT_EXIST"
    CLOSEOUT_POSITION_INCOMPLETE_SPECIFICATION = "CLOSEOUT_POSITION_INCOMPLETE_SPECIFICATION"
    CLOSEOUT_POSITION_UNITS_EXCEED_POSITION_SIZE = "CLOSEOUT_POSITION_UNITS_EXCEED_POSITION_SIZE"
    CLOSEOUT_POSITION_REJECT = "CLOSEOUT_POSITION_REJECT"
    CLOSEOUT_POSITION_PARTIAL_UNITS_MISSING = "CLOSEOUT_POSITION_PARTIAL_UNITS_MISSING"
    MARKUP_GROUP_ID_INVALID = "MARKUP_GROUP_ID_INVALID"
    POSITION_AGGREGATION_MODE_INVALID = "POSITION_AGGREGATION_MODE_INVALID"
    ADMIN_CONFIGURE_DATA_MISSING = "ADMIN_CONFIGURE_DATA_MISSING"
    MARGIN_RATE_INVALID = "MARGIN_RATE_INVALID"
    MARGIN_RATE_WOULD_TRIGGER_CLOSEOUT = "MARGIN_RATE_WOULD_TRIGGER_CLOSEOUT"
    ALIAS_INVALID = "ALIAS_INVALID"
    CLIENT_CONFIGURE_DATA_MISSING = "CLIENT_CONFIGURE_DATA_MISSING"
    MARGIN_RATE_WOULD_TRIGGER_MARGIN_CALL = "MARGIN_RATE_WOULD_TRIGGER_MARGIN_CALL"
    AMOUNT_INVALID = "AMOUNT_INVALID"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    AMOUNT_MISSING = "AMOUNT_MISSING"
    FUNDING_REASON_MISSING = "FUNDING_REASON_MISSING"
    OCA_ORDER_IDS_STOP_LOSS_NOT_ALLOWED = "OCA_ORDER_IDS_STOP_LOSS_NOT_ALLOWED"
    CLIENT_EXTENSIONS_DATA_MISSING = "CLIENT_EXTENSIONS_DATA_MISSING"
    REPLACING_ORDER_INVALID = "REPLACING_ORDER_INVALID"
    REPLACING_TRADE_ID_INVALID = "REPLACING_TRADE_ID_INVALID"
    ORDER_CANCEL_WOULD_TRIGGER_CLOSEOUT = "ORDER_CANCEL_WOULD_TRIGGER_CLOSEOUT"
    # Additional values not present on the OANDA transaction-df page but kept for
    # backwards compatibility with older library users:
    MARKET_HALTED = "MARKET_HALTED"
    ORDER_ID_INVALID = "ORDER_ID_INVALID"


class FundingReason(str, Enum):
    """Reasons for funding transactions."""

    CLIENT_FUNDING = "CLIENT_FUNDING"
    ACCOUNT_TRANSFER = "ACCOUNT_TRANSFER"
    DIVISION_MIGRATION = "DIVISION_MIGRATION"
    SITE_MIGRATION = "SITE_MIGRATION"
    ADJUSTMENT = "ADJUSTMENT"


class GuaranteedStopLossOrderMode(str, Enum):
    """The overall behaviour of an Account regarding guaranteed Stop Loss Orders."""

    DISABLED = "DISABLED"
    ALLOWED = "ALLOWED"
    REQUIRED = "REQUIRED"


class GuaranteedStopLossOrderMutability(str, Enum):
    """Actions that can be performed on guaranteed Stop Loss Orders."""

    FIXED = "FIXED"
    REPLACEABLE = "REPLACEABLE"
    CANCELABLE = "CANCELABLE"
    PRICE_WIDEN_ONLY = "PRICE_WIDEN_ONLY"


class AccountFinancingMode(str, Enum):
    """The financing mode of an Account."""

    NO_FINANCING = "NO_FINANCING"
    SECOND_BY_SECOND = "SECOND_BY_SECOND"
    DAILY = "DAILY"


class PositionAggregationMode(str, Enum):
    """The way that position values for an Account are calculated and aggregated."""

    ABSOLUTE_SUM = "ABSOLUTE_SUM"
    MAXIMAL_SIDE = "MAXIMAL_SIDE"
    NET_SUM = "NET_SUM"


class DayOfWeek(str, Enum):
    """Standard day-of-week enumeration."""

    SUNDAY = "SUNDAY"
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"


class GuaranteedStopLossOrderModeForInstrument(str, Enum):
    """Guaranteed stop loss availability per instrument."""

    DISABLED = "DISABLED"  # Not available for this instrument
    ALLOWED = "ALLOWED"  # Available but optional
    REQUIRED = "REQUIRED"  # Required for all positions


class TradeStateFilter(str, Enum):
    """The state to filter the Trades by."""

    OPEN = "OPEN"  # Currently open trades
    CLOSED = "CLOSED"  # Fully closed trades
    CLOSE_WHEN_TRADEABLE = "CLOSE_WHEN_TRADEABLE"  # Pending closure
    ALL = "ALL"  # All trades regardless of state


class TradePL(str, Enum):
    """The classification of TradePLs."""

    POSITIVE = "POSITIVE"  # Profitable trade P/L
    NEGATIVE = "NEGATIVE"  # Losing trade P/L
    ZERO = "ZERO"  # Zero P/L trade


class OrderStateFilter(str, Enum):
    """Filter Orders by OrderState for aggregation."""

    PENDING = "PENDING"  # Only pending orders
    FILLED = "FILLED"  # Only filled orders
    TRIGGERED = "TRIGGERED"  # Only triggered orders
    CANCELLED = "CANCELLED"  # Only cancelled orders
    ALL = "ALL"  # All orders regardless of state


class CancellableOrderType(str, Enum):
    """The type of Order that can be cancelled."""

    LIMIT = "LIMIT"
    STOP = "STOP"
    MARKET_IF_TOUCHED = "MARKET_IF_TOUCHED"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    GUARANTEED_STOP_LOSS = "GUARANTEED_STOP_LOSS"
    TRAILING_STOP_LOSS = "TRAILING_STOP_LOSS"


class PriceStatus(str, Enum):
    """Current status of an instrument's pricing."""

    tradeable = "tradeable"  # Instrument is actively tradeable
    non_tradeable = "non-tradeable"  # Instrument is not currently tradeable
    invalid = "invalid"  # Pricing information is invalid


# Type aliases (not classes to avoid Pydantic issues)
AccountID = str
"""Account identifier in format: {site}-{division}-{user}-{account}."""

TradeID = str
"""Trade identifier unique within the Account."""

OrderID = str
"""Order identifier unique within the Account."""

TransactionID = str
"""Transaction identifier unique within the Account."""

RequestID = str
"""Request identifier for correlation."""

PriceValue = Decimal
"""Price value handled as Decimal internally, serialized as string for API precision."""

AccountUnits = Decimal
"""Account currency units handled as Decimal internally, serialized as string for API precision."""

PricingComponent = str
"""Price component selector for candlestick data, such as M, B, A, BA, BM, AM, or BAM."""


class OrderCancelReason(str, Enum):
    """The reason that an Order was cancelled."""

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_NEW_POSITIONS_LOCKED = "ACCOUNT_NEW_POSITIONS_LOCKED"
    ACCOUNT_ORDER_CREATION_LOCKED = "ACCOUNT_ORDER_CREATION_LOCKED"
    ACCOUNT_ORDER_FILL_LOCKED = "ACCOUNT_ORDER_FILL_LOCKED"
    CLIENT_REQUEST = "CLIENT_REQUEST"
    MIGRATION = "MIGRATION"
    MARKET_HALTED = "MARKET_HALTED"
    LINKED_TRADE_CLOSED = "LINKED_TRADE_CLOSED"
    TIME_IN_FORCE_EXPIRED = "TIME_IN_FORCE_EXPIRED"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    FIFO_VIOLATION = "FIFO_VIOLATION"
    BOUNDS_VIOLATION = "BOUNDS_VIOLATION"
    CLIENT_REQUEST_REPLACED = "CLIENT_REQUEST_REPLACED"
    DIVIDEND_ADJUSTMENT_REPLACED = "DIVIDEND_ADJUSTMENT_REPLACED"
    INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY"
    TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST = "TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    TAKE_PROFIT_ON_FILL_LOSS = "TAKE_PROFIT_ON_FILL_LOSS"
    LOSING_TAKE_PROFIT = "LOSING_TAKE_PROFIT"
    STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    STOP_LOSS_ON_FILL_LOSS = "STOP_LOSS_ON_FILL_LOSS"
    STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    STOP_LOSS_ON_FILL_REQUIRED = "STOP_LOSS_ON_FILL_REQUIRED"
    STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED = "STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED"
    STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED = "STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED"
    STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET = "STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET"
    STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED = "STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED"
    STOP_LOSS_ON_FILL_GUARANTEED_HEDGING_NOT_ALLOWED = "STOP_LOSS_ON_FILL_GUARANTEED_HEDGING_NOT_ALLOWED"
    STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID = "STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID"
    STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID = "STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    GUARANTEED_STOP_LOSS_ON_FILL_LOSS = "GUARANTEED_STOP_LOSS_ON_FILL_LOSS"
    GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED = "GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED"
    GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED = "GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED"
    GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET = "GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET"
    GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED = "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED"
    GUARANTEED_STOP_LOSS_ON_FILL_HEDGING_NOT_ALLOWED = "GUARANTEED_STOP_LOSS_ON_FILL_HEDGING_NOT_ALLOWED"
    GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID"
    GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID = "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID"
    TAKE_PROFIT_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED = "TAKE_PROFIT_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED"
    TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST = "TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST"
    CLIENT_TRADE_ID_ALREADY_EXISTS = "CLIENT_TRADE_ID_ALREADY_EXISTS"
    POSITION_CLOSEOUT_FAILED = "POSITION_CLOSEOUT_FAILED"
    OPEN_TRADES_ALLOWED_EXCEEDED = "OPEN_TRADES_ALLOWED_EXCEEDED"
    PENDING_ORDERS_ALLOWED_EXCEEDED = "PENDING_ORDERS_ALLOWED_EXCEEDED"
    TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS = "TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS"
    STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS = "STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS"
    GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS = "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS"
    TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS = "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS"
    POSITION_SIZE_EXCEEDED = "POSITION_SIZE_EXCEEDED"
    HEDGING_GSLO_VIOLATION = "HEDGING_GSLO_VIOLATION"
    ACCOUNT_POSITION_VALUE_LIMIT_EXCEEDED = "ACCOUNT_POSITION_VALUE_LIMIT_EXCEEDED"
    INSTRUMENT_BID_REDUCE_ONLY = "INSTRUMENT_BID_REDUCE_ONLY"
    INSTRUMENT_ASK_REDUCE_ONLY = "INSTRUMENT_ASK_REDUCE_ONLY"
    INSTRUMENT_BID_HALTED = "INSTRUMENT_BID_HALTED"
    INSTRUMENT_ASK_HALTED = "INSTRUMENT_ASK_HALTED"
    STOP_LOSS_ON_FILL_GUARANTEED_BID_HALTED = "STOP_LOSS_ON_FILL_GUARANTEED_BID_HALTED"
    STOP_LOSS_ON_FILL_GUARANTEED_ASK_HALTED = "STOP_LOSS_ON_FILL_GUARANTEED_ASK_HALTED"
    GUARANTEED_STOP_LOSS_ON_FILL_BID_HALTED = "GUARANTEED_STOP_LOSS_ON_FILL_BID_HALTED"
    GUARANTEED_STOP_LOSS_ON_FILL_ASK_HALTED = "GUARANTEED_STOP_LOSS_ON_FILL_ASK_HALTED"
    FIFO_VIOLATION_SAFEGUARD_VIOLATION = "FIFO_VIOLATION_SAFEGUARD_VIOLATION"
    FIFO_VIOLATION_SAFEGUARD_PARTIAL_CLOSE_VIOLATION = "FIFO_VIOLATION_SAFEGUARD_PARTIAL_CLOSE_VIOLATION"
    ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION = "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION"


class OrderFillReason(str, Enum):
    """The reason that an Order was filled."""

    LIMIT_ORDER = "LIMIT_ORDER"
    STOP_ORDER = "STOP_ORDER"
    MARKET_IF_TOUCHED_ORDER = "MARKET_IF_TOUCHED_ORDER"
    TAKE_PROFIT_ORDER = "TAKE_PROFIT_ORDER"
    STOP_LOSS_ORDER = "STOP_LOSS_ORDER"
    GUARANTEED_STOP_LOSS_ORDER = "GUARANTEED_STOP_LOSS_ORDER"
    TRAILING_STOP_LOSS_ORDER = "TRAILING_STOP_LOSS_ORDER"
    MARKET_ORDER = "MARKET_ORDER"
    MARKET_ORDER_TRADE_CLOSE = "MARKET_ORDER_TRADE_CLOSE"
    MARKET_ORDER_POSITION_CLOSEOUT = "MARKET_ORDER_POSITION_CLOSEOUT"
    MARKET_ORDER_MARGIN_CLOSEOUT = "MARKET_ORDER_MARGIN_CLOSEOUT"
    MARKET_ORDER_DELAYED_TRADE_CLOSE = "MARKET_ORDER_DELAYED_TRADE_CLOSE"
    FIXED_PRICE_ORDER = "FIXED_PRICE_ORDER"
    FIXED_PRICE_ORDER_PLATFORM_ACCOUNT_MIGRATION = "FIXED_PRICE_ORDER_PLATFORM_ACCOUNT_MIGRATION"
    FIXED_PRICE_ORDER_DIVISION_ACCOUNT_MIGRATION = "FIXED_PRICE_ORDER_DIVISION_ACCOUNT_MIGRATION"
    FIXED_PRICE_ORDER_ADMINISTRATIVE_ACTION = "FIXED_PRICE_ORDER_ADMINISTRATIVE_ACTION"


class MarketOrderReason(str, Enum):
    """The reason that the Market Order was created."""

    CLIENT_ORDER = "CLIENT_ORDER"
    TRADE_CLOSE = "TRADE_CLOSE"
    POSITION_CLOSEOUT = "POSITION_CLOSEOUT"
    MARGIN_CLOSEOUT = "MARGIN_CLOSEOUT"
    DELAYED_TRADE_CLOSE = "DELAYED_TRADE_CLOSE"


class LimitOrderReason(str, Enum):
    """The reason that the Limit Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"


class StopOrderReason(str, Enum):
    """The reason that the Stop Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"


class MarketIfTouchedOrderReason(str, Enum):
    """The reason that the Market-if-touched Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"


class TakeProfitOrderReason(str, Enum):
    """The reason that the Take Profit Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"
    ON_FILL = "ON_FILL"


class StopLossOrderReason(str, Enum):
    """The reason that the Stop Loss Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"
    ON_FILL = "ON_FILL"


class TrailingStopLossOrderReason(str, Enum):
    """The reason that the Trailing Stop Loss Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"
    ON_FILL = "ON_FILL"


class GuaranteedStopLossOrderReason(str, Enum):
    """The reason that the Guaranteed Stop Loss Order was initiated."""

    CLIENT_ORDER = "CLIENT_ORDER"
    REPLACEMENT = "REPLACEMENT"
    ON_FILL = "ON_FILL"


class MarketOrderMarginCloseoutReason(str, Enum):
    """The reason that the Market Order was created to perform a margin closeout."""

    MARGIN_CHECK_VIOLATION = "MARGIN_CHECK_VIOLATION"
    REGULATORY_MARGIN_CALL_VIOLATION = "REGULATORY_MARGIN_CALL_VIOLATION"
    REGULATORY_MARGIN_CHECK_VIOLATION = "REGULATORY_MARGIN_CHECK_VIOLATION"


class FixedPriceOrderReason(str, Enum):
    """The reason that the Fixed Price Order was created."""

    PLATFORM_ACCOUNT_MIGRATION = "PLATFORM_ACCOUNT_MIGRATION"
    TRADE_CLOSE_DIVISION_ACCOUNT_MIGRATION = "TRADE_CLOSE_DIVISION_ACCOUNT_MIGRATION"
    TRADE_CLOSE_ADMINISTRATIVE_ACTION = "TRADE_CLOSE_ADMINISTRATIVE_ACTION"
